project_id = "gwyjgljnpntorbjphnbq"

[functions.paystack-payment]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.vtu-service]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.support-chat]
verify_jwt = false

[functions.cleanup-deleted-accounts]
verify_jwt = false

[functions.get-security-question]
verify_jwt = false

[functions.verify-smartcard]
verify_jwt = false

[functions.verify-meter]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.verify-internet]
verify_jwt = false
