// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsqefyykvxwmbwdnzvtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzcWVmeXlrdnh3bWJ3ZG56dnRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU3Nzc0MTcsImV4cCI6MjEwMTM1MzQxN30.4bVkaNKc0zYz0uBKysBxOFLhPohK2ng8io5v2jhHCqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});